---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    environment_config:
      NODE_ENV: production
      ENVIRONMENT: production
      TYPEORM_CONNECTION: postgres
      TYPEORM_ENTITIES: /root/backend_app/modules/domain/**/*.entity.js
      TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
  roles:
    - role: weareinteractive.environment
      become: true
    # - role: configure-server
    #   become: true
    - role: deploy
      become: true
