- name: Copy backend files
  become: true
  copy:
    src: backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Install node -v12
  shell: |
    sudo apt update
    sudo apt -y upgrade
    sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt -y install nodejs

- name: Start backend Server
  shell: |
    cd /home/ubuntu/
    tar xzvf backend.tar.gz
    sudo npm install

    sudo pm2 start npm --name backend -- start
